################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utility/stale/tinydbwraper/test \
utility/stale/tinydbwraper \
utility/stale/test/sunion/src \
utility/stale/runtime \
utility/stale/boxes \
utility/client/region \
utility/client/region/.libs \
utility/client/java/src \
utility/client/java/src/clientApi \
utility/client/global \
tool/optimizer/loadShedder \
tool/optimizer/loadManager \
tool/optimizer \
tool/marshal \
tool/loadGenerator/wlgen \
tool/loadGenerator/simple \
tool/head \
tool/head/.libs \
test/valid/two_chains \
test/valid/system \
test/valid/revisions \
test/valid/move \
test/valid/global \
test/valid/deploy \
test/valid/connect \
test/valid/catalog \
test/valid/array \
test/unit \
test/simple \
test/developer \
test/composite/updates \
test/composite/sunion/src \
test/composite/revision \
test/composite/loadnetwork \
test/composite/loadbox \
test/composite/fault \
test/composite/deltaProcessing/video \
test/composite/deltaProcessing/stars \
test/composite/deltaProcessing/ais \
test/composite/NHLoadShedder \
test/composite/GlobalLoadShedder/chain \
src/src \
src/modules/util \
src/modules/util/.libs \
src/modules/queryProcessor/storageMgr \
src/modules/queryProcessor/storageMgr/.libs \
src/modules/queryProcessor/statsMgr \
src/modules/queryProcessor/statsMgr/.libs \
src/modules/queryProcessor/runtime \
src/modules/queryProcessor/runtime/.libs \
src/modules/queryProcessor/expr \
src/modules/queryProcessor/expr/.libs \
src/modules/queryProcessor/boxes \
src/modules/queryProcessor/boxes/.libs \
src/modules/queryProcessor \
src/modules/queryProcessor/.libs \
src/modules/optimizer/nhopt \
src/modules/optimizer/nhopt/.libs \
src/modules/optimizer/local \
src/modules/optimizer/local/.libs \
src/modules/ha \
src/modules/ha/.libs \
src/modules/common \
src/modules/common/.libs \
src/modules/catalog \
src/modules/catalog/.libs \
src/modules/availMon \
src/modules/availMon/.libs \
src/external/udb/stub \
src/external/udb/stub/.libs \
src/external/udb \
src/external \
src/external/bdb/stub \
src/external/bdb/stub/.libs \
src/external/bdb \
src/external/array/stub \
src/external/array/stub/.libs \
src/external/array \
src/external/.libs \
demo/sigmod2005/cube/bot_src/src \
demo/sigmod2005/cube/bot_src/enet \
demo/parallel \
demo/mitre \
demo/ids \
demo/ha \
demo/contrast_decision \
demo/contrast_composite \
demo/array \

