import clientApi.*;

/**
 * The Schema class (should be automatically generated by the java marshaling tool)
 *
 * @author Jeong-Hyon Hwang (jhhwang@cs.brown.edu)
 * @version 1.0 03/07/2005
 */
public class CountSchema
    extends Tuple {

  public int source;
  public int timestamp;
  public int count;

  public CountSchema() {
    this(0, 0, 0);
  }

  public CountSchema(int source, int timestamp, int count) {
    this.source = source;
    this.timestamp = timestamp;
    this.count = count;
  }

  public String toString() {
    String s = "(";
    s += "source = ";
    s += source;
    s += ", timestamp = ";
    s += timestamp;
    s += ", count = ";
    s += count;
    return s + ")";
  }
}

