import clientApi.*;

/**
 * The Schema class (should be automatically generated by the java marshaling tool)
 *
 * @author Jeong-Hyon Hwang (jhhwang@cs.brown.edu)
 * @version 1.0 03/07/2005
 */
public class DistanceSchema
    extends Tuple {

//  public long timestamp;
  public long timestamp;
  public int distance;
  public int seq_no;

  public DistanceSchema() {
    this(0, 0, 0);
  }

  public DistanceSchema(long timestamp, int distance, int seq_no) {
    this.timestamp = timestamp;
    this.distance = distance;
    this.seq_no = seq_no;
  }

  public String toString() {
    String s = "(timestamp = ";
    s += timestamp;
    s += ", distance = ";
    s += distance;
    s += ", seq_no = ";
    s += seq_no;
    return s + ")";
  }
}

