import clientApi.*;

/**
 * The Schema class (should be automatically generated by the java marshaling tool)
 *
 * @author Jeong-Hyon Hwang (jhhwang@cs.brown.edu)
 * @version 1.0 03/07/2005
 */
public class PacketSchema
    extends Tuple {

  public int timestamp;
  public int source;
  public int destination;
  public int size;

  public PacketSchema() {
    this(0, 0, 0, 0);
  }

  public PacketSchema(int timestamp, int source, int destination, int size) {
    this.timestamp = timestamp;
    this.source = source;
    this.destination = destination;
    this.size = size;
  }

  public String toString() {
    String s = "(";
    s += "timestamp = ";
    s += timestamp;
    s += ", source = ";
    s += source;
    s += ", destination = ";
    s += destination;
    s += ", size = ";
    s += size;
    return s + ")";
  }
}

