import clientApi.*;

/**
 * The AppElement class (should be automatically generated by the java marshaling tool)
 *
 * @author Jeong-Hyon Hwang (jhhwang@cs.brown.edu)
 * @version 1.0 02/04/2005
 */
public class AppElement
    extends Tuple {

  public int timestamp;
  public int id;
  public int x;
  public int y;
  public int color;

  public AppElement() {
    this.timestamp = 0;
    this.id = 0;
    this.x = 0;
    this.y = 0;
    this.color = 0;
  }

  public AppElement(int timestamp, int id, int x,
                 int y, int color) {
    this.timestamp = timestamp;
    this.id = id;
    this.x = x;
    this.y = y;
    this.color = color;
  }

  public String toString() {
    String s = "(";
    s += timestamp;
    s += ", ";
    s += id;
    s += ", ";
    s += x;
    s += ", ";
    s += y;
    s += ", ";
    s += color;
    return s+")";
  }

}