import clientApi.*;

/**
 * The ImageData class (should be automatically generated by the java marshaling tool)
 *
 * @author Jeong-Hyon Hwang (jhhwang@cs.brown.edu)
 * @version 1.0 02/04/2005
 */
public class ImageData
    extends Tuple {

  public int timestamp;
  public int frame_index;
  public int row_index_begin;
  public int row_index_end;
  public byte[] image_data;

  public ImageData() {
    this(0, 0, 0, 0);
  }

  public ImageData(int timestamp, int frame_index, int row_index_begin,
                   int row_index_end) {
    this.timestamp = timestamp;
    this.frame_index = frame_index;
    this.row_index_begin = row_index_begin;
    this.row_index_end = row_index_end;
    this.image_data = new byte[352];
    for (int i = 0; i < 352; i++) {
      this.image_data[i] = 0;
    }
  }

  public ImageData(int timestamp, int frame_index, int row_index_begin,
                   int row_index_end, byte[] image_data) {
    this.timestamp = timestamp;
    this.frame_index = frame_index;
    this.row_index_begin = row_index_begin;
    this.row_index_end = row_index_end;
    this.image_data = image_data;
  }

  public String toString() {
    String s = "(";
    s += timestamp;
    s += ", ";
    s += frame_index;
    s += ", ";
    s += row_index_begin;
    s += ", ";
    s += row_index_end;
    return s+")";
  }

}