#ifndef  MARSHALDIAGRAM_H
#define  MARSHALDIAGRAM_H

#include "Diagram.h"

BOREALIS_NAMESPACE_BEGIN

class MarshalDiagram : public Diagram
{

  public:

    /// Reparse Schemas, Inputs and Outputs to add extra diagram items.
    ///
    Status  parse_marshal();


    /// Establish the default prefix for the client name.
    ///
    void  setDefaultPrefix(/// The first relative XML file path.
                           /// 
                           string  xml_file);



    /// Map lowercase schema names to upper case.
    ///
    map<string, string>           _schema_mixed;


    ///  Automatically fill in deployment for a simple network.
    ///
    Status  generate_deployment();


    ///  Determine the schemas for pending intermediate streams.
    ///
    Status  infer_schema();


  private:

    /// Reparse Publish elements to add extra diagram items.
    ///
    Status  reparse_publish(const  DOMElement *root,
                                       string  prefix);


  protected:

    ///  Capitalize the first letter in a sequence of alphabetic characters.
    ///
    static  void  proper_case(/// Symbolic name to format.
                              string  &name );


    /// While parsing this contains the default prefix for the client name.
    /// When generating code it has the prefix for the current client name.
    /// A default prefix is extracted from the first XML file or it is
    /// specified on a client element.  It is stored using proper case.
    ///
    string        _prefix;


    // Catalog.h has the _publisher_map: map<InetAddress, SubscriptionMap>
    // SubscriptionMap:  map<Name, CatalogSubscription>
    // CatalogSubscription:  {InetAddress, Name, CatalogStream*, ...}

    /// Programs that are to be generated.
    /// Note that an input can only be generated by one program.
    ///
    struct  GeneratePublish
    {   string          _prefix;    // Client feeding the stream (proper case).
        vector<string>  _node;      // Node for each _publish stream.
                                    // If empty infer nodes from boxes.
                                    // Endpoints are in canonical form.
    };


    /// Map each published stream (lowercase) to it's client and initial nodes.
    ///
    map<string, GeneratePublish>  _generate_publish;


    /// Map each client's name prefix (proper case) to it's monitor endpoint
    /// (canonical form).  Actually, just a port is needed as it is always
    /// the localhost???
    ///
    map<string, string>      _generate_client;
};

BOREALIS_NAMESPACE_END
#endif                       // MARSHALDIAGRAM_H
