#!/bin/bash

# Adjust the debug level
export LOG_LEVEL="0 Admin.cc:2"

if [ $# -lt 1 ]
then
    echo " Try: ./rundemo start"
    exit 0
fi
	
# What to start
what=$1

# --------------------------------------------------
# Configurable variables (you may need to change these)
# --------------------------------------------------
# Get the IP address of this machine on its Ethernet connection
#IP=`/sbin/ifconfig eth0 | grep inet | awk '{print $2}' | sed 's#addr:##g'`
IP=${IP:-"127.0.0.1"}

# Looking for CLS_IP and BOREALIS_HOME environment variables 
# These variables give the top
# level location of all the source code. If they are not
# defined, assign them some reasonable defaults
BOREALIS_HOME=${BOREALIS_HOME:-"${HOME}/borealis"}

# The IP address where the CentralLookupServer will be running
CLS_IP=${CLS_IP:-"${IP}"}

# The Borealis config file that defines the contracts and "process-pairs"
CONFIG_FILE=${CONFIG_FILE:-"medusa_config.xml"}

# Second, we configure the port numbers that will be used by all the 
# applications
CLS_PORT=30000 # Port of the CentralLookupServer
BOREALIS_DATA_PORT=15000
BOREALIS_QUERY1_PORT=17000
PORT_DELTA=100

# Create more ports using the PORT_DELTA
for i in `seq 1 7`
do
    for j in `seq 1 7`
    do
        let "BOREALIS_QUERY${i}${j}_PORT = BOREALIS_QUERY${i}_PORT+${j}*${PORT_DELTA}"
    done
done

CLIENT_PORTS_PREFIX=4000  # clients will use 40001, 40002, etc.

# Assuming CentralLookupServer will be running at node 1
export BOREALIS_CLS=${CLS_IP}:${CLS_PORT}

# Make sure Aurora gives itself enough memory
export AURORA_PAGES=10000
export AURORA_PAGE_SIZE=16384

# --------------------------------------------------
# Everything else below should get set automatically
# --------------------------------------------------
BOREALIS_SRC_HOME=${BOREALIS_HOME}/src/src

# Staing CLS
case "${what}" in 

    # --------------------------------------------------
    # Basic targets
    # --------------------------------------------------

    cls)
        if [ "${IP}" != "${CLS_IP}" ]
        then
            eval echo "If you want to run CLS here, then please adjust CLS_IP in script to match ${IP}"
            exit 0
        fi
        echo "Starting CLS..."
        BINDING=${IP}:${CLS_PORT}
        eval echo "xterm -T CLS@${BINDING} -geometry 80x10+20+20 -e ${BOREALIS_SRC_HOME}/CentralLookupServer -d ${BINDING}"
        xterm -T CLS@${BINDING} -geometry 80x10+20+20 -e sh -c "${BOREALIS_SRC_HOME}/CentralLookupServer -d ${BINDING} 2>&1 |tee cls-${BINDING}.log"  &
        echo "CLS started."
        ;;

    borealis)
        echo "Starting Borealis Data"
        eval echo "Assuming CLS is running at: ${BOREALIS_CLS}"
        if [ $# -gt 1 ] 
        then
            BOREALIS_PORT=$2
            OTHER_OPTIONS=$3 # There might be none
        else
            BOREALIS_PORT=${BOREALIS_DATA_PORT}
        fi
        BINDING=${IP}:${BOREALIS_PORT}
        eval echo "xterm -T Borealis@${BINDING} -geometry 80x10+20+20 -e ${BOREALIS_SRC_HOME}/borealis -d ${BINDING} -f ${CONFIG_FILE} ${OTHER_OPTIONS}"
        xterm -T Borealis@${BINDING} -geometry 80x10+20+50 -e sh -c "${BOREALIS_SRC_HOME}/borealis -d ${BINDING}  -f ${CONFIG_FILE} ${OTHER_OPTIONS} 2>&1 |tee borealis-${BINDING}.log" &
        echo "Borealis started."
        ;;

     client)
        echo "Starting ids using new API"
        if [ $# -lt 5 ] 
        then
            echo "To run an ids client you must specify the client number," 
            echo "the port of the borealis node for the query, the trace file, and the speedup factor"
            exit 0
        fi
        CLIENT_PORT=${CLIENT_PORTS_PREFIX}$2
        BOREALIS_QUERY_PORT=$3
        TRACE=$4
        SPEEDUP=$5
        BINDING=${IP}:${CLIENT_PORT}
        eval echo "xterm -T ids@${BINDING} -geometry 80x10+20+50 -e ./ids -a ${BINDING}  -f ${TRACE} -r ${SPEEDUP}" &
        xterm -T ids@${BINDING} -geometry 80x10+250+50 -e sh -c "./ids -a ${BINDING} -d ${IP}:${BOREALIS_DATA_PORT} -f ${TRACE} -r ${SPEEDUP} 2>&1 |tee ids-${BINDING}.log" &
        echo "Client started"
        ;;

    # --------------------------------------------------
    # Composite targets
    # --------------------------------------------------

    start)
        $0 cls
        sleep 4
        $0 borealis ${BOREALIS_DATA_PORT} 
        sleep 2
        $0 borealis ${BOREALIS_QUERY15_PORT}
        sleep 2
        $0 borealis ${BOREALIS_QUERY16_PORT}
        sleep 2
        $0 client 1 ${BOREALIS_QUERY15_PORT} simple-trace.dat 5

        exit 0
        ;;

     stop)
        killall xterm.real
	killall xterm
        exit 0
        ;;
esac

